### ISSUE TITLE
HelmRelease backup failure in 2.10.6, 3.0.3 and 3.1.0 versions

### ISSUE THREAD

**Issue by josedev-union** [triliovault-k8s-issues/triliovault-k8s-issues#32]
## Issue Description
Backup of a helm release is failing at the first step (`MetaSnapshot`).
I can backup using the label instead and all steps including `MetaSnapshot`, `ImageBackup`, `DataSnapshot`, `DataUpload`, `MetadataUpload`, and `Cleanup` are successful. So I can say the underlying infra(K8s, CSI, Backup storage backend) are functioning correctly.

### Preconditions
0. tvk-preflight passed
1. k8s flavour: RKE2
2. k8s version: 1.25.7
3. storage: Openstack Cinder CSI
4. CSI version: We use the mixed versions as following because Openstack version is a bit old.
```
k8s.gcr.io/sig-storage/csi-provisioner:v3.1.1
k8s.gcr.io/sig-storage/csi-snapshotter:v6.2.0
docker.io/k8scloudprovider/cinder-csi-plugin:v1.21.0
```
5. k8s TrilioVault version: 3.1.0, 3.0.3, 2.10.6 (i tried these 3 versions and all have this same issue)
6. Target: AWS S3 (by using s3proxy backed by Openstack swift)
7. BackupPlan: 
```yaml
apiVersion: triliovault.trilio.io/v1
kind: BackupPlan
metadata:
  annotations:
    triliovault.trilio.io/creator: operator boi
    triliovault.trilio.io/instance-id: 3aa2b2f9-3e60-4f8f-a8f5-829485dee5fc
  creationTimestamp: "2023-05-04T16:45:39Z"
  generation: 1
  name: helmrelease-backup-1
  namespace: testing1
  resourceVersion: "13739931"
  uid: 53fcad9c-44c9-461d-bedd-a4efb8b816c7
spec:
  backupConfig:
    target:
      apiVersion: triliovault.trilio.io/v1
      kind: Target
      name: demo-s3-target
      namespace: testing1
      resourceVersion: "13734917"
      uid: 9a2af350-bdcd-4792-a325-ec205fee4b8c
  backupPlanComponents:
    helmReleases:
    - mariadb
  backupPlanFlags:
    skipImageBackup: true
status:
  applicationType: Helm
  condition:
  - phase: Sync
    reason: Sync InProgress
    status: InProgress
    timestamp: "2023-05-04T16:45:39Z"
  - phase: Sync
    reason: Sync Completed
    status: Completed
    timestamp: "2023-05-04T16:45:39Z"
  scope: App
  stats:
    backupSummary:
      latestBackup:
        apiVersion: triliovault.trilio.io/v1
        kind: Backup
        name: mariadb-backup
        namespace: testing1
        resourceVersion: "13739930"
        uid: 393fc629-3516-46ca-a048-008ff58de4a1
      pvcExistsForBackup: false
      totalFailedBackups: 1
    restoreSummary: {}
  status: Available
```
8. Backup
```yaml
apiVersion: triliovault.trilio.io/v1
kind: Backup
metadata:
  annotations:
    triliovault.trilio.io/creator: operator boi
    triliovault.trilio.io/instance-id: 3aa2b2f9-3e60-4f8f-a8f5-829485dee5fc
    triliovault.trilio.io/updater: '[{"username":"system:serviceaccount:trilio-system:k8s-triliovault","lastUpdatedTimestamp":"2023-05-04T16:45:54.479230913Z"}]'
  creationTimestamp: "2023-05-04T16:45:54Z"
  finalizers:
  - backup-cleanup-finalizer
  generation: 1
  labels:
    app.kubernetes.io/managed-by: k8s-triliovault-ui
    app.kubernetes.io/name: k8s-triliovault
    app.kubernetes.io/part-of: k8s-triliovault
  name: mariadb-backup
  namespace: testing1
  resourceVersion: "13739930"
  uid: 393fc629-3516-46ca-a048-008ff58de4a1
spec:
  backupPlan:
    apiVersion: triliovault.trilio.io/v1
    kind: BackupPlan
    name: helmrelease-backup-1
    namespace: testing1
    resourceVersion: "13738781"
    uid: 53fcad9c-44c9-461d-bedd-a4efb8b816c7
  type: Full
status:
  applicationType: Helm
  backupScope: App
  completionTimestamp: "2023-05-04T16:47:27Z"
  condition:
  - phase: MetaSnapshot
    reason: MetaSnapshot InProgress
    status: InProgress
    timestamp: "2023-05-04T16:45:59Z"
  - phase: MetaSnapshot
    reason: MetaSnapshot Failed
    status: Failed
    timestamp: "2023-05-04T16:46:10Z"
  - phase: MetadataUpload
    reason: MetadataUpload InProgress
    status: InProgress
    timestamp: "2023-05-04T16:46:15Z"
  - phase: MetadataUpload
    reason: MetadataUpload Completed
    status: Completed
    timestamp: "2023-05-04T16:47:27Z"
  duration: 1m33.947612861s
  encryptionEnabled: false
  location: 53fcad9c-44c9-461d-bedd-a4efb8b816c7/393fc629-3516-46ca-a048-008ff58de4a1
  metadataSize: "0"
  phase: MetadataUpload
  phaseStatus: Completed
  size: "0"
  startTimestamp: "2023-05-04T16:45:54Z"
  stats:
    hookExists: false
    targetInfo:
      target:
        apiVersion: triliovault.trilio.io/v1
        kind: Target
        name: demo-s3-target
        namespace: testing1
        resourceVersion: "13734917"
        uid: 9a2af350-bdcd-4792-a325-ec205fee4b8c
      type: ObjectStore
      vendor: AWS
  status: Failed
  type: Full
```
9. Target
```yaml
apiVersion: triliovault.trilio.io/v1
kind: Target
metadata:
  annotations:
    triliovault.trilio.io/creator: user-4q4j4
    triliovault.trilio.io/credentials-hash: "445432208"
    triliovault.trilio.io/instance-id: 3aa2b2f9-3e60-4f8f-a8f5-829485dee5fc
    triliovault.trilio.io/owner-namespace: trilio-system
    triliovault.trilio.io/updater: '[{"username":"system:serviceaccount:trilio-system:k8s-triliovault","lastUpdatedTimestamp":"2023-05-04T15:34:12.007704469Z"},{"username":"operator
      boi","lastUpdatedTimestamp":"2023-05-04T15:34:10.360023969Z"},{"username":"system:serviceaccount:testing1:triliovault-target-9a2af350-bdcd-4792-a325-ec205fee4b8c","lastUpdatedTimestamp":"2023-05-04T15:33:02.555991762Z"}]'
  creationTimestamp: "2023-05-04T05:27:05Z"
  generation: 5
  labels:
    app.kubernetes.io/managed-by: k8s-triliovault-webhook
    triliovault.trilio.io/cloned: "true"
  name: demo-s3-target
  namespace: testing1
  resourceVersion: "13743819"
  uid: 9a2af350-bdcd-4792-a325-ec205fee4b8c
spec:
  nfsCredentials:
    nfsExport: ""
  objectStoreCredentials:
    bucketName: Trilio
    credentialSecret:
      apiVersion: v1
      kind: Secret
      name: s3proxy-local
      namespace: testing1
      resourceVersion: "13336397"
      uid: dd9b06f9-5a9f-4900-b203-6f1f36b9508d
    region: udlm-syd2
    url: https://s3proxy.default.svc
  thresholdCapacity: 50Gi
  type: ObjectStore
  vendor: AWS
status:
  condition:
  - reason: Target credentials changed.
    timestamp: "2023-05-04T05:27:05Z"
  - phase: Validation
    reason: Validation InProgress
    status: InProgress
    timestamp: "2023-05-04T05:27:05Z"
  - phase: Validation
    reason: Validation Completed
    status: Completed
    timestamp: "2023-05-04T05:27:26Z"
  - phase: TargetBrowsing
    reason: Browsing is enabled, waiting for target browser deployment and service
      to come up.
    status: InProgress
    timestamp: "2023-05-04T12:59:37Z"
  - phase: TargetBrowsing
    reason: Successfully enabled target browser
    status: Completed
    timestamp: "2023-05-04T13:53:11Z"
  - phase: TargetBrowsing
    reason: Browsing is disabled, deleting deployment and service for target browser.
    status: InProgress
    timestamp: "2023-05-04T15:34:11Z"
  - phase: TargetBrowsing
    reason: Successfully disabled target browser.
    status: Completed
    timestamp: "2023-05-04T15:34:11Z"
  stats:
    applicationCapacity: "27917287424"
    applicationCapacityConsumed: "27917287424"
    capacityOccupied: "814219264"
    totalBackupPlans: 5
  status: Available
```

### Steps to reproduce
All resource manfiests have been mentioned above, and the steps are normal to create a backup of a helm release.
- 1. Create a target named `demo-s3-target`
- 2. Create a backup plan named `helmrelease-backup-1`
- 3. Create a backup named `mariadb-backup`
Then the backup failed at `MetaSnapshot` step. I dumped the full yaml of resources which includes the status also.

### Actual and Expected result
- Expected result:
Backup status changes to Available
- Actual result:
Backup status changed to Failed. It was failed at `MetaSnapshot` step, more specifically, metamover job was failed.

### Support Log Bundle

Here is the full logs of the failed `metamover` job.

```
{"level": "info", "file": "/opt/tvk/datastore-attacher/mount_utility/mount_by_target_crd/mount_datastores.py:55", "func": "main", "time": "2023-05-05T09:17:08Z", "service_type": "MetaSnapshot", "service_id": "077c88bb-e88e-41e4-80e1-b0be342a3a9a", "tvk_version": "3.1.0", "tvk_instance_id": "8941b02d-cd23-4df2-a403-c9da40f18e4c", "transaction_type": "Target", "group": "triliovault.trilio.io", "transaction_id": "", "transaction_resource_name": "demo-s3-target", "transaction_resource_namespace": "trilio-test", "msg": "Fetching target cr to get the datastore"}
{"level": "info", "file": "/opt/tvk/datastore-attacher/mount_utility/mount_by_target_crd/triliodata_crd_parser.py:69", "func": "get_ds_from_target_crds", "time": "2023-05-05T09:17:08Z", "service_type": "MetaSnapshot", "service_id": "077c88bb-e88e-41e4-80e1-b0be342a3a9a", "tvk_version": "3.1.0", "tvk_instance_id": "8941b02d-cd23-4df2-a403-c9da40f18e4c", "transaction_type": "Target", "group": "triliovault.trilio.io", "transaction_id": "", "transaction_resource_name": "demo-s3-target", "transaction_resource_namespace": "trilio-test", "msg": "fetching target-cr for group: triliovault.trilio.io"}
{"level": "info", "file": "/opt/tvk/datastore-attacher/mount_utility/mount_by_target_crd/mount_datastores.py:60", "func": "main", "time": "2023-05-05T09:17:08Z", "service_type": "MetaSnapshot", "service_id": "077c88bb-e88e-41e4-80e1-b0be342a3a9a", "tvk_version": "3.1.0", "tvk_instance_id": "8941b02d-cd23-4df2-a403-c9da40f18e4c", "transaction_type": "Target", "group": "triliovault.trilio.io", "transaction_id": "", "transaction_resource_name": "demo-s3-target", "transaction_resource_namespace": "trilio-test", "msg": "Fetched the list of datastores to be mounted"}
{"level": "info", "file": "/opt/tvk/datastore-attacher/mount_utility/utilities.py:426", "func": "mount_datastore", "time": "2023-05-05T09:17:08Z", "service_type": "MetaSnapshot", "service_id": "077c88bb-e88e-41e4-80e1-b0be342a3a9a", "tvk_version": "3.1.0", "tvk_instance_id": "8941b02d-cd23-4df2-a403-c9da40f18e4c", "transaction_type": "Target", "group": "triliovault.trilio.io", "transaction_id": "89848b8a-c1e6-4b48-a87f-e575febce0f6", "transaction_resource_name": "demo-s3-target", "transaction_resource_namespace": "trilio-test", "msg": "Mounting datastore of type objectstore"}
{"level": "info", "file": "/opt/tvk/datastore-attacher/mount_utility/utilities.py:296", "func": "mount_s3_datastore", "time": "2023-05-05T09:17:08Z", "service_type": "MetaSnapshot", "service_id": "077c88bb-e88e-41e4-80e1-b0be342a3a9a", "tvk_version": "3.1.0", "tvk_instance_id": "8941b02d-cd23-4df2-a403-c9da40f18e4c", "transaction_type": "Target", "group": "triliovault.trilio.io", "transaction_id": "89848b8a-c1e6-4b48-a87f-e575febce0f6", "transaction_resource_name": "demo-s3-target", "transaction_resource_namespace": "trilio-test", "msg": "Mounting the objectstore datastore by the name demo-s3-target"}
{"level": "info", "file": "/opt/tvk/datastore-attacher/mount_utility/utilities.py:326", "func": "mount_s3_datastore", "time": "2023-05-05T09:17:08Z", "service_type": "MetaSnapshot", "service_id": "077c88bb-e88e-41e4-80e1-b0be342a3a9a", "tvk_version": "3.1.0", "tvk_instance_id": "8941b02d-cd23-4df2-a403-c9da40f18e4c", "transaction_type": "Target", "group": "triliovault.trilio.io", "transaction_id": "89848b8a-c1e6-4b48-a87f-e575febce0f6", "transaction_resource_name": "demo-s3-target", "transaction_resource_namespace": "trilio-test", "msg": "Writing the conf data to the conf file: /tmp/trilio-tmp/vault.conf\n"}
{"level": "info", "file": "/opt/tvk/datastore-attacher/mount_utility/utilities.py:342", "func": "mount_s3_datastore", "time": "2023-05-05T09:17:08Z", "service_type": "MetaSnapshot", "service_id": "077c88bb-e88e-41e4-80e1-b0be342a3a9a", "tvk_version": "3.1.0", "tvk_instance_id": "8941b02d-cd23-4df2-a403-c9da40f18e4c", "transaction_type": "Target", "group": "triliovault.trilio.io", "transaction_id": "89848b8a-c1e6-4b48-a87f-e575febce0f6", "transaction_resource_name": "demo-s3-target", "transaction_resource_namespace": "trilio-test", "msg": "command: /usr/bin/python3 /opt/tvk/datastore-attacher/mount_utility/run_fuse_in_background.py &"}
{"level": "info", "file": "/opt/tvk/datastore-attacher/mount_utility/utilities.py:99", "func": "run_cmd", "time": "2023-05-05T09:17:08Z", "service_type": "MetaSnapshot", "service_id": "077c88bb-e88e-41e4-80e1-b0be342a3a9a", "tvk_version": "3.1.0", "tvk_instance_id": "8941b02d-cd23-4df2-a403-c9da40f18e4c", "transaction_type": "Target", "group": "triliovault.trilio.io", "transaction_id": "89848b8a-c1e6-4b48-a87f-e575febce0f6", "transaction_resource_name": "demo-s3-target", "transaction_resource_namespace": "trilio-test", "msg": "Executing command /usr/bin/python3 /opt/tvk/datastore-attacher/mount_utility/run_fuse_in_background.py &"}
{"level": "info", "file": "/opt/tvk/datastore-attacher/mount_utility/utilities.py:100", "func": "run_cmd", "time": "2023-05-05T09:17:08Z", "service_type": "MetaSnapshot", "service_id": "077c88bb-e88e-41e4-80e1-b0be342a3a9a", "tvk_version": "3.1.0", "tvk_instance_id": "8941b02d-cd23-4df2-a403-c9da40f18e4c", "transaction_type": "Target", "group": "triliovault.trilio.io", "transaction_id": "89848b8a-c1e6-4b48-a87f-e575febce0f6", "transaction_resource_name": "demo-s3-target", "transaction_resource_namespace": "trilio-test", "msg": "/usr/bin/python3 /opt/tvk/datastore-attacher/mount_utility/run_fuse_in_background.py & command execution starting time: 2023-05-05 09:17:08.943036"}
{"level": "info", "file": "/opt/tvk/datastore-attacher/mount_utility/utilities.py:113", "func": "run_cmd", "time": "2023-05-05T09:17:08Z", "service_type": "MetaSnapshot", "service_id": "077c88bb-e88e-41e4-80e1-b0be342a3a9a", "tvk_version": "3.1.0", "tvk_instance_id": "8941b02d-cd23-4df2-a403-c9da40f18e4c", "transaction_type": "Target", "group": "triliovault.trilio.io", "transaction_id": "89848b8a-c1e6-4b48-a87f-e575febce0f6", "transaction_resource_name": "demo-s3-target", "transaction_resource_namespace": "trilio-test", "msg": "waiting for command to complete..."}
{"level": "info", "file": "/usr/lib/python3.8/site-packages/s3fuse/s3vaultfuse.py:576", "func": "run", "time": "2023-05-05T09:17:10Z", "service_type": "", "service_id": "077c88bb-e88e-41e4-80e1-b0be342a3a9a", "tvk_version": "3.1.0", "tvk_instance_id": "8941b02d-cd23-4df2-a403-c9da40f18e4c", "transaction_type": "Target", "group": "", "transaction_id": "", "transaction_resource_name": "", "transaction_resource_namespace": "", "msg": "Starting worker thread[7f2747fff700]."}
{"level": "info", "file": "/opt/tvk/datastore-attacher/mount_utility/utilities.py:118", "func": "run_cmd", "time": "2023-05-05T09:17:10Z", "service_type": "MetaSnapshot", "service_id": "077c88bb-e88e-41e4-80e1-b0be342a3a9a", "tvk_version": "3.1.0", "tvk_instance_id": "8941b02d-cd23-4df2-a403-c9da40f18e4c", "transaction_type": "Target", "group": "triliovault.trilio.io", "transaction_id": "89848b8a-c1e6-4b48-a87f-e575febce0f6", "transaction_resource_name": "demo-s3-target", "transaction_resource_namespace": "trilio-test", "msg": "/usr/bin/python3 /opt/tvk/datastore-attacher/mount_utility/run_fuse_in_background.py & command execution completion time: 2023-05-05 09:17:10.949543"}
{"level": "info", "file": "/opt/tvk/datastore-attacher/mount_utility/utilities.py:128", "func": "run_cmd", "time": "2023-05-05T09:17:10Z", "service_type": "MetaSnapshot", "service_id": "077c88bb-e88e-41e4-80e1-b0be342a3a9a", "tvk_version": "3.1.0", "tvk_instance_id": "8941b02d-cd23-4df2-a403-c9da40f18e4c", "transaction_type": "Target", "group": "triliovault.trilio.io", "transaction_id": "89848b8a-c1e6-4b48-a87f-e575febce0f6", "transaction_resource_name": "demo-s3-target", "transaction_resource_namespace": "trilio-test", "msg": "Command:/usr/bin/python3 /opt/tvk/datastore-attacher/mount_utility/run_fuse_in_background.py &, ExitCode:0\n"}
{"level": "info", "file": "/opt/tvk/datastore-attacher/mount_utility/utilities.py:358", "func": "wait_until_mount", "time": "2023-05-05T09:17:10Z", "service_type": "MetaSnapshot", "service_id": "077c88bb-e88e-41e4-80e1-b0be342a3a9a", "tvk_version": "3.1.0", "tvk_instance_id": "8941b02d-cd23-4df2-a403-c9da40f18e4c", "transaction_type": "Target", "group": "triliovault.trilio.io", "transaction_id": "89848b8a-c1e6-4b48-a87f-e575febce0f6", "transaction_resource_name": "demo-s3-target", "transaction_resource_namespace": "trilio-test", "msg": "2023-05-05 09:17:10.950862: Waiting for mount operation to complete."}
{"level": "info", "file": "/opt/tvk/datastore-attacher/mount_utility/utilities.py:362", "func": "wait_until_mount", "time": "2023-05-05T09:17:10Z", "service_type": "MetaSnapshot", "service_id": "077c88bb-e88e-41e4-80e1-b0be342a3a9a", "tvk_version": "3.1.0", "tvk_instance_id": "8941b02d-cd23-4df2-a403-c9da40f18e4c", "transaction_type": "Target", "group": "triliovault.trilio.io", "transaction_id": "89848b8a-c1e6-4b48-a87f-e575febce0f6", "transaction_resource_name": "demo-s3-target", "transaction_resource_namespace": "trilio-test", "msg": "2023-05-05 09:17:10.952008: Target mounted successfully."}
{"level": "info", "file": "/opt/tvk/datastore-attacher/mount_utility/utilities.py:350", "func": "mount_s3_datastore", "time": "2023-05-05T09:17:10Z", "service_type": "MetaSnapshot", "service_id": "077c88bb-e88e-41e4-80e1-b0be342a3a9a", "tvk_version": "3.1.0", "tvk_instance_id": "8941b02d-cd23-4df2-a403-c9da40f18e4c", "transaction_type": "Target", "group": "triliovault.trilio.io", "transaction_id": "89848b8a-c1e6-4b48-a87f-e575febce0f6", "transaction_resource_name": "demo-s3-target", "transaction_resource_namespace": "trilio-test", "msg": "Removing all the vault files from the ./tmp directory"}
{"level": "info", "file": "/usr/local/lib/python3.8/site-packages/setuptools/_distutils/dir_util.py:219", "func": "remove_tree", "time": "2023-05-05T09:17:10Z", "service_type": "MetaSnapshot", "service_id": "077c88bb-e88e-41e4-80e1-b0be342a3a9a", "tvk_version": "3.1.0", "tvk_instance_id": "8941b02d-cd23-4df2-a403-c9da40f18e4c", "transaction_type": "Target", "group": "triliovault.trilio.io", "transaction_id": "89848b8a-c1e6-4b48-a87f-e575febce0f6", "transaction_resource_name": "demo-s3-target", "transaction_resource_namespace": "trilio-test", "msg": "removing '/tmp/trilio-tmp' (and everything under it)"}


I0505 09:17:12.235713       1 request.go:682] Waited for 1.039084042s due to client-side throttling, not priority and fairness, request: GET:https://10.43.0.1:443/apis/networking.k8s.io/v1?timeout=32s
{"file":"cmd/metamover/metamover.go:10","func":"main.main","level":"info","msg":"Starting the Metadata Processing...","service_id":"077c88bb-e88e-41e4-80e1-b0be342a3a9a","service_type":"MetaMover","time":"2023-05-05T09:17:12Z","tvk_instance_id":"8941b02d-cd23-4df2-a403-c9da40f18e4c","tvk_version":"3.1.0"}
{"file":"cmd/metamover/app/snapshot.go:66","func":"github.com/trilioData/k8s-triliovault/v2/cmd/metamover/app.runSnapshotE","level":"info","msg":"Starting Metadata Snapshot operation for Backup trilio-test/helmrelease-mariadb-backup","service_id":"077c88bb-e88e-41e4-80e1-b0be342a3a9a","service_type":"MetaMover","time":"2023-05-05T09:17:12Z","tvk_instance_id":"8941b02d-cd23-4df2-a403-c9da40f18e4c","tvk_version":"3.1.0"}
{"file":"internal/helpers/commons.go:110","func":"github.com/trilioData/k8s-triliovault/v2/internal/helpers.ValidateDataStorePath","level":"info","msg":"DataStore path [/triliodata] validated successfully","service_id":"077c88bb-e88e-41e4-80e1-b0be342a3a9a","service_type":"MetaMover","time":"2023-05-05T09:17:12Z","tvk_instance_id":"8941b02d-cd23-4df2-a403-c9da40f18e4c","tvk_version":"3.1.0"}
{"file":"pkg/metamover/snapshot/snapshot_utils.go:52","func":"github.com/trilioData/k8s-triliovault/v2/pkg/metamover/snapshot.getBackupPlanByObjectReference","level":"info","msg":"Using reference [triliovault.trilio.io/v1, Kind=BackupPlan] Name=helmrelease-mariadb-backup for metadata snapshot","service_id":"077c88bb-e88e-41e4-80e1-b0be342a3a9a","service_type":"MetaSnapshot","time":"2023-05-05T09:17:12Z","transaction_id":"9cfbaf67-98a8-4f14-a1d4-65b80d073c88","transaction_resource_name":"helmrelease-mariadb-backup","transaction_resource_namespace":"trilio-test","transaction_type":"Backup","tvk_instance_id":"8941b02d-cd23-4df2-a403-c9da40f18e4c","tvk_version":"3.1.0"}
{"file":"pkg/metamover/snapshot/snapshot_utils.go:69","func":"github.com/trilioData/k8s-triliovault/v2/pkg/metamover/snapshot.GetFullMetaDataSnapshot","level":"info","msg":"Checking whether metadata snapshot for application needed...","service_id":"077c88bb-e88e-41e4-80e1-b0be342a3a9a","service_type":"MetaSnapshot","time":"2023-05-05T09:17:12Z","transaction_id":"9cfbaf67-98a8-4f14-a1d4-65b80d073c88","transaction_resource_name":"helmrelease-mariadb-backup","transaction_resource_namespace":"trilio-test","transaction_type":"Backup","tvk_instance_id":"8941b02d-cd23-4df2-a403-c9da40f18e4c","tvk_version":"3.1.0"}
{"file":"pkg/metamover/snapshot/snapshot_utils.go:72","func":"github.com/trilioData/k8s-triliovault/v2/pkg/metamover/snapshot.GetFullMetaDataSnapshot","level":"info","msg":"Snapshot operation started for snapshot type(BackupScope)=App","service_id":"077c88bb-e88e-41e4-80e1-b0be342a3a9a","service_type":"MetaSnapshot","time":"2023-05-05T09:17:12Z","transaction_id":"9cfbaf67-98a8-4f14-a1d4-65b80d073c88","transaction_resource_name":"helmrelease-mariadb-backup","transaction_resource_namespace":"trilio-test","transaction_type":"Backup","tvk_instance_id":"8941b02d-cd23-4df2-a403-c9da40f18e4c","tvk_version":"3.1.0"}
{"file":"pkg/metamover/snapshot/applications/helm.go:59","func":"github.com/trilioData/k8s-triliovault/v2/pkg/metamover/snapshot/applications.(*Helm).snapshot","level":"info","msg":"Metadata snapshot started for Helm=mariadb","service_id":"077c88bb-e88e-41e4-80e1-b0be342a3a9a","service_type":"MetaSnapshot","time":"2023-05-05T09:17:12Z","transaction_id":"9cfbaf67-98a8-4f14-a1d4-65b80d073c88","transaction_resource_name":"helmrelease-mariadb-backup","transaction_resource_namespace":"trilio-test","transaction_type":"Backup","tvk_instance_id":"8941b02d-cd23-4df2-a403-c9da40f18e4c","tvk_version":"3.1.0"}
{"file":"internal/helm_utils/helm3.go:854","func":"github.com/trilioData/k8s-triliovault/v2/internal/helm_utils.pullDependency","level":"info","msg":"Processing dependency: [common]","service_id":"077c88bb-e88e-41e4-80e1-b0be342a3a9a","service_type":"MetaSnapshot","time":"2023-05-05T09:17:12Z","transaction_id":"9cfbaf67-98a8-4f14-a1d4-65b80d073c88","transaction_resource_name":"helmrelease-mariadb-backup","transaction_resource_namespace":"trilio-test","transaction_type":"Backup","tvk_instance_id":"8941b02d-cd23-4df2-a403-c9da40f18e4c","tvk_version":"3.1.0"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x2fd7c84]

goroutine 204 [running]:
github.com/trilioData/k8s-triliovault/v2/vendor/helm.sh/helm/v3/pkg/registry.(*Client).Pull(0x0, {0xc001302646?, 0xc00061d7b0?}, {0x0, 0x0, 0x3?})
	vendor/helm.sh/helm/v3/pkg/registry/client.go:303 +0x424
github.com/trilioData/k8s-triliovault/v2/vendor/helm.sh/helm/v3/pkg/getter.(*OCIGetter).get(0xc00061d7d0?, {0xc001302640, 0x3f})
	vendor/helm.sh/helm/v3/pkg/getter/ocigetter.go:53 +0x274
github.com/trilioData/k8s-triliovault/v2/vendor/helm.sh/helm/v3/pkg/getter.(*OCIGetter).Get(0xc000129760, {0xc001302640, 0x3f}, {0xc0012d4840, 0x5, 0x7f969145dfb0?})
	vendor/helm.sh/helm/v3/pkg/getter/ocigetter.go:36 +0x70
github.com/trilioData/k8s-triliovault/v2/vendor/helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo(0xc00061dc78, {0xc0013024c0, 0x39}, {0xc00133adf6?, 0x1?}, {0xc0012a91a0, 0x14})
	vendor/helm.sh/helm/v3/pkg/downloader/chart_downloader.go:100 +0xea
github.com/trilioData/k8s-triliovault/v2/vendor/helm.sh/helm/v3/pkg/action.(*Pull).Run(0xc000664380, {0xc0013024c0, 0x39})
	vendor/helm.sh/helm/v3/pkg/action/pull.go:126 +0xb85
github.com/trilioData/k8s-triliovault/v2/internal/helm_utils.pullDependency(0xc0009e8780?, 0xc0004de410, 0x19bd566?, 0x0?)
	internal/helm_utils/helm3.go:890 +0xa90
github.com/trilioData/k8s-triliovault/v2/internal/helm_utils.pullWorker(0xc00004eb40, 0x1b4e4ea?, 0xc00004eae0, 0x0?)
	internal/helm_utils/helm3.go:991 +0x53
created by github.com/trilioData/k8s-triliovault/v2/internal/helm_utils.(*helmV3StorageBackend).ProcessDependencies
	internal/helm_utils/helm3.go:686 +0x61b
```

**Comment by madhurtrilio** [comment]
@josedev-union we are looking into this issue

**Comment by josedev-union** [comment]
> @josedev-union we are looking into this issue

@madhurtrilio thanks.
If you need any furthur infor, please let me know. Also i can contribute to if needed.

**Comment by josedev-union** [comment]
@madhurtrilio did you have a chance to reproduce this issue?

**Comment by madhurtrilio** [comment]
Hi @josedev-union , we were able to reproduce the issue. 
TVK tries to pull helm chart dependencies if there are any mentioned in the chart.yaml file of helm chart.
In case of mariadb the dependency is commons which is hosted on repository which is using oci protocol
<img width="482" alt="image" src="https://github.com/triliovault-k8s-issues/triliovault-k8s-issues/assets/48991399/89e02129-ca26-4740-a891-1df40c10c286">

TVK right now does not support oci based repositories. We will add a fix for this and will make it available in our upcoming patch release 3.0.4. The due date for the same is 10th June.

**Comment by josedev-union** [comment]
> Hi @josedev-union , we were able to reproduce the issue. TVK tries to pull helm chart dependencies if there are any mentioned in the chart.yaml file of helm chart. In case of mariadb the dependency is commons which is hosted on repository which is using oci protocol <img alt="image" width="482" src="https://user-images.githubusercontent.com/48991399/238900043-89e02129-ca26-4740-a891-1df40c10c286.png">
> 
> TVK right now does not support oci based repositories. We will add a fix for this and will make it available in our upcoming patch release 3.0.4. The due date for the same is 10th June.

@madhurtrilio  Aha got it. We can avoid using oci charts as dependecies before a new version release.
Thanks 👍

**Comment by madhurtrilio** [comment]
@josedev-union Patch release 3.0.4 is released and it fixes the oci repository issue. Please check

**Comment by josedev-union** [comment]
> @josedev-union Patch release 3.0.4 is released and it fixes the oci repository issue. Please check

@madhurtrilio sweet. let me test on my side
